CPUThreshold=95
MemThreshold=95
ThresholdDuration=60
PollInterval=5
ProcessName=test-service.sh
ScriptsDir=/usr/lib/hgw_doctor/actions
DiagOutputDir=/tmp/hgw_diag
ODLPath=/etc/amx/hgw_doctor/hgw_doctor.odl