CPUThreshold=25
MemThreshold=15
ThresholdDuration=5
PollInterval=5
ProcessList=cwmp_plugin,tr181-device,dhcpv4-manager,tr181-dns,test-service
ScriptsDir=/usr/lib/hgw_doctor/actions
DiagOutputDir=/tmp/hgw_diag
ODLPath=/etc/amx/hgw_doctor/hgw_doctor.odl