CPUThreshold=90
MemThreshold=90
ThresholdDuration=60
PollInterval=5
ProcessList=cwmp_plugin,tr181-device,dhcpv4-manager,tr181-dns,test-service
ScriptsDir=/usr/lib/hgw_doctor/actions
AllowReboot=false
EnableWatchdog=false
DiagOutputDir=/tmp/hgw_diag
ODLPath=/etc/amx/hgw_doctor/hgw_doctor.odl
